export const footerTitle = 'Software Testing Project'
export const headerTitle = 'Employee CRUD Application'
export const employeeCreatePage = 'Create Employee'
export const employeeUpdatePage = 'Update Employee'
export const employeeCreateBtn = 'Create'
export const employeeUpdateBtn = 'Update'
export const FooterCopyRight='software testing project all right reserved'
