name: tests
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install dependencies and run project tests
        working-directory: ./software-testing-project/frontend
        run: npm install && npm run test:ci && docker build -t mohsinwaseem65/CRUD-frontend
      - name: Docker login
        working-directory: ./software-testing-project/frontend
        run: docker login -u mohsinwaseem65 -p Mrvsk12678@wa
      - name: Docker build image and push to docker hub
        run: docker push mohsinwaseem65/CRUD-frontend
